# Build customization
builds:
  -
    main: ./cmd/tilecutter/main.go
    binary: tilecutter
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
  -
    main: ./cmd/tileflipper/main.go
    binary: tileflipper
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
  -
    main: ./cmd/tileslicer/main.go
    binary: tileslicer
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
# Archive customization
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: x86_64
    386: i686
    darwin: macOS
  files:
    - README.md
    - LICENSE
snapcraft:
  summary: Command-line tools to process tile set images
  description: |
    Provides tileslicer, tilejoiner, tilecutter and tileflipper commands.
  grade: beta
  confinement: strict
  apps:
    tilecutter:
      plugs: ["home"]
    tilejoiner:
      plugs: ["home"]
    tileslicer:
      plugs: ["home"]
    tileflipper:
      plugs: ["home"]
